name: Generate PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://pandoc/latex:2.9
        with:
          path: .
          args: "--output=README.pdf README.md" # gets appended to pandoc command